name: Production Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.EC2_PRIVATE_KEY }}

    - name: Deploy to EC2
      env:
        APP_DIR: /home/ubuntu/my-app
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          set -e
          if [ ! -d "$APP_DIR/.git" ]; then
            git clone https://github.com/boygeek743-ops/my-app.git $APP_DIR
          fi
          cd $APP_DIR
          git reset --hard origin/main
          npm install --production
          pm2 stop all || true
          pm2 start index.js --name "my-app"
          pm2 save
          echo "Deployment completed successfully!"
EOF
