- name: Deploy to EC2
  run: |
    ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
      set -e

      APP_DIR=/home/ubuntu/my-app

      # Clone if repo doesn't exist
      if [ ! -d "$APP_DIR/.git" ]; then
        echo "Cloning repository..."
        git clone https://github.com/boygeek743-ops/my-app.git $APP_DIR
      fi

      cd $APP_DIR
      git reset --hard origin/main

      echo "Installing dependencies..."
      npm install --production

      echo "Restarting app with PM2..."
      pm2 stop all || true
      pm2 start index.js --name "my-app"
      pm2 save

      echo "Deployment completed successfully!"
EOF
